# Generated by Django 2.2.6 on 2019-11-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='open_date',
            field=models.DateField(),
        ),
    ]
